### ISSUE TITLE
Fail to run quick start example

### ISSUE THREAD

**Issue by manuzhang** [alexarchambault/ammonite-spark#29]
The [quick-start example in README](https://github.com/alexarchambault/ammonite-spark#quick-start) with following errors

```
java.lang.NoClassDefFoundError: ammonite/ops/PathConvertible
  org.apache.spark.sql.AmmoniteSparkSession$.builder(AmmoniteSparkSession.scala:32)
  ammonite.$sess.cmd3$.<init>(cmd3.sc:2)
  ammonite.$sess.cmd3$.<clinit>(cmd3.sc)
java.lang.ClassNotFoundException: ammonite.ops.PathConvertible
  java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:215)
  java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  org.apache.spark.sql.AmmoniteSparkSession$.builder(AmmoniteSparkSession.scala:32)
  ammonite.$sess.cmd3$.<init>(cmd3.sc:2)
  ammonite.$sess.cmd3$.<clinit>(cmd3.sc)
```

ammonite version: 1.6.0
spark version: 2.3.1
ammonite-spark version: 0.1.1

**Comment by alexarchambault** [comment]
@manuzhang There are restrictions on which ammonite-spark versions are compatible with particular Ammonite versions.

IIRC, ammonite-spark `0.2.0` should be used along Ammonite `1.6.0`. And ammonite-spark `0.3.0` with the current Ammonite `1.6.3`.

**Comment by manuzhang** [comment]
Sure, maybe update the README ?

**Comment by alexarchambault** [comment]
Done in https://github.com/alexarchambault/ammonite-spark/commit/fdf90cb9e85a27163fa1fa370d5fe4301a14ee4a.

**Comment by mahiki** [comment]
It still isn't clear from the readme that the dependencies are specific to only the versions listed above (0.3.0 and 1.6.3). The readme says

>Start Ammonite >= 1.6.3, with the --class-based option. Either follow *the instructions* on its website, then do

So greater than or equal to 1.6.3 will work? This issue says no. Anyway I'd love to use this but i think I've spent too much time trying to figure this out. For example, the 'the instructions' link on the wiki is just the whole front page of the Ammonite-REPL.

I did:

```bash
brew install ammonite-repl
# this is 2.0.1

amm --class-based
import $ivy.`org.apache.spark::spark-sql:2.4.0`

Failed to resolve ivy dependencies:Error downloading org.apache.spark:spark-sql_2.13:2.4.0
  not found: /Users/XXXXX/.ivy2/local/org.apache.spark/spark-sql_2.13/2.4.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.13/2.4.0/spark-sql_2.13-2.4.0.pom
```

I use spark/scala at work, but this level of detail on dependencies has me lost.

**Comment by manuzhang** [comment]
> So greater than or equal to 1.6.3 will work? This issue says no

@mahiki 
Note in my issue it's ammonite-spark 0.1.1 doesn't work with ammonite 1.6.0. 

Looking at your errors, I think the cause is the scala version. I don't think Spark works with Scala 2.13 yet.
